name: Lint and Unit Test

on:
  pull_request:

  workflow_run:
    types: [completed]
    workflows: [Enforce Gitflow]

jobs:
  lint:
    if: github.event.pull_request.draft == false
    name: Lint and Unit Test
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Detect affected projects
        uses: nrwl/nx-set-shas@v4
      
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
          
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track ${{ github.base_ref }} origin/${{ github.base_ref }}
        if: ${{ github.event_name == 'pull_request' }}

      - name: Lint
        run: pnpm lint:all

      - name: Test
        run: pnpm test:affected
